1) Explore more regex patterns Eg. The regex pattern used to validate email addresses, mobile no, string, and more

In [19]:
import re

email = "abc@gmail.com"

pattern = r'.+@.+\..+'

if re.match(pattern, email):
    print("Valid Email")
else:
    print("Invalid Email")

Valid Email

In [20]:
mobile = "9876543210"

pattern = r'^[0-9]{10}$'

if re.match(pattern, mobile):
    print("Valid Number")
else:
    print("Invalid Number")

Valid Number

In [21]:
name = "Akshat"

pattern = r'^[A-Za-z]+$'

if re.match(pattern, name):
    print("Valid String")
else:
    print("Invalid String")

Valid String

In [22]:
password = "abc123"

pattern = r'^[A-Za-z0-9]+$'

if re.match(pattern, password):
    print("Valid Password")
else:
    print("Invalid Password")

Valid Password

2) Explore more datetime function and uses in pandas

In [1]:
import pandas as pd

dates = pd.to_datetime([
    '2025-01-01',
    '2025-02-15',
    '2025-03-20'
])

dates

DatetimeIndex(['2025-01-01', '2025-02-15', '2025-03-20'], dtype='datetime64[ns]', freq=None)

In [5]:
pd.Timestamp.now()

Timestamp('2026-05-27 18:13:08.190104')

In [8]:
df = pd.DataFrame({
    'Date': pd.to_datetime(['2025-01-01', '2025-06-15'])
})

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

df['Day_Name'] = df['Date'].dt.day_name()

df

        Date  Year  Month  Day   Day_Name
0 2025-01-01  2025      1    1  Wednesday
1 2025-06-15  2025      6   15     Sunday

In [18]:
start = pd.to_datetime('2025-01-01')
end = pd.to_datetime('2025-01-10')

difference = end - start
difference

Timedelta('9 days 00:00:00')

3) Import an meaningful csv file for data analysis and perform data cleaning, and analysis for meaningful output

In [9]:
df = pd.read_csv("Address Book.csv")

df

     name    address      mobile             email
0  akshat  jagatpura  4214211512  akshat@email.com
1   vidhi  jagatpura  3413413414   vidhi@email.com
2  updesh  durgapura  1421424212  updesh@email.com

In [10]:
print(df.isnull().sum())

name       0
address    0
mobile     0
email      0
dtype: int64

In [16]:
df['address'].unique()

array(['jagatpura', 'durgapura'], dtype=object)

In [12]:
print(df['address'].value_counts())

address
jagatpura    2
durgapura    1
Name: count, dtype: int64

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mobile,3.0,3.016350e+09,1.438110e+09,1.421424e+09,2.417419e+09,3.413413e+09,3.813812e+09,4.214212e+09